FROM debian:bookworm-slim

# Define version
ARG PHP_VERSION=8.2
ARG SIMPLESAMLPHP_VERSION=2.3.5

# Install necessary packages
RUN apt-get update \
    && apt-get install -y \
        apache2 \
        php${PHP_VERSION} \
        php${PHP_VERSION}-mysqli \
        php${PHP_VERSION}-xml \
        php${PHP_VERSION}-curl \
        php${PHP_VERSION}-intl \
        php${PHP_VERSION}-pdo-sqlite \
        php${PHP_VERSION}-mbstring \
        php${PHP_VERSION}-ldap \
        php${PHP_VERSION}-http \
        php${PHP_VERSION}-raphf \
        curl \
        git \
        unzip \
        wget \
        nano \
        mariadb-server \
        supervisor \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ARG COMPOSER_ALLOW_SUPERUSER=1

# Set the working directory
WORKDIR /


# Enable Apache mod_rewrite
# RUN a2enmod php
# RUN a2enmod rewrite

# Download and set up SimpleSAMLphp
RUN wget https://github.com/simplesamlphp/simplesamlphp/releases/download/v${SIMPLESAMLPHP_VERSION}/simplesamlphp-${SIMPLESAMLPHP_VERSION}-full.tar.gz \
    && tar -xzf simplesamlphp-${SIMPLESAMLPHP_VERSION}-full.tar.gz -C /var \
    && mv /var/simplesamlphp-${SIMPLESAMLPHP_VERSION} /var/simplesamlphp \
    && rm simplesamlphp-${SIMPLESAMLPHP_VERSION}-full.tar.gz

# Set up configuration directory
RUN mkdir -p /var/simplesamlphp/config /var/simplesamlphp/metadata

# Copy Apache configuration for SimpleSAMLphp
COPY apache-simplesaml.conf /etc/apache2/sites-available/simplesaml.conf
RUN a2ensite simplesaml.conf && a2dissite 000-default.conf


# Set ownership and permissions
RUN chown -R www-data:www-data /var/simplesamlphp && chmod -R 755 /var/simplesamlphp

# Expose web server port
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]
