# BASE: "http://localhost:8000"
# COOKIE_STATE_NAME: "SATOSA_STATE"
# INTERNAL_ATTRIBUTES: "config/internal_attributes.yaml"

# BACKEND_MODULES:
#   - "satosa.backends.saml2.SAMLBackend"
#     config:
#       entityid: "http://localhost:8000/backend.xml"
#       metadata:
#         local:
#           - "config/idp_metadata.xml"

# FRONTEND_MODULES:
#   - "satosa.frontends.saml2.SAMLFrontend"
#     config:
#       entityid: "http://localhost:8000/proxy.xml"
#       metadata:
#         local:
#           - "config/sp_metadata.xml"

# MICRO_SERVICES: []


BASE: "http://localhost:8000"
COOKIE_STATE_NAME: "SATOSA_STATE"
STATE_ENCRYPTION_KEY: "CHANGE_THIS_SECRET"

INTERNAL_ATTRIBUTES: "config/internal_attributes.yaml"

BACKEND_MODULES:
  - "satosa.backends.saml2.SAMLBackend"
    config:
      entityid: "http://localhost:8000/backend.xml"
      metadata:
        local:
          - "config/idp_metadata.xml"

FRONTEND_MODULES:
  - "satosa.frontends.saml2.SAMLFrontend"
    config:
      entityid: "http://localhost:8000/proxy.xml"
      metadata:
        local:
          - "config/sp_metadata.xml"

MICRO_SERVICES: []
